In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 2s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.12932958, -0.28727904,  0.32058206, -0.4646599 , -0.16919726,
         0.19106686, -0.5351031 , -0.01314759,  0.09076033,  0.15516542]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.11630791, 0.07667935, 0.14082155, 0.06421594, 0.08629004,
        0.12371472, 0.05984803, 0.10086308, 0.1119074 , 0.11935198]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.089777

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2970 - accuracy: 0.9137
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1429 - accuracy: 0.9582
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1063 - accuracy: 0.9681
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0878 - accuracy: 0.9733
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0762 - accuracy: 0.9766


In [10]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [11]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[8.6142977e-09, 7.9480078e-10, 1.9988449e-06, 2.9408815e-04,
        5.4637740e-12, 1.7923185e-08, 3.0873161e-13, 9.9970335e-01,
        1.5150441e-07, 2.9780301e-07],
       [9.6013908e-10, 2.7552058e-04, 9.9971360e-01, 7.9249530e-06,
        1.2963353e-13, 2.9422074e-06, 3.1962494e-10, 2.9468165e-13,
        1.2409213e-08, 2.8708620e-12],
       [4.7283311e-08, 9.9846482e-01, 2.3386827e-05, 2.7871072e-06,
        2.4884512e-05, 1.4772508e-05, 2.1581865e-05, 1.2501668e-03,
        1.9596363e-04, 1.6193133e-06],
       [9.9965405e-01, 2.6610140e-08, 2.7326896e-04, 2.5623410e-07,
        3.0857311e-07, 1.9159557e-07, 2.1727017e-06, 6.2014296e-05,
        3.2883840e-08, 7.7385102e-06],
       [1.5999654e-05, 2.8908149e-09, 2.6693682e-05, 1.4449506e-07,
        9.8915344e-01, 5.4348416e-06, 2.4377207e-05, 2.2008686e-04,
        9.1513803e-06, 1.0544747e-02]], dtype=float32)>